### ISSUE TITLE
Offline banner not shown when app opened with no network.

### ISSUE THREAD

**Issue by HyzamAli** [mitchtabian/food2fork-compose#3]
To reproduce
- Turn of wifi/cellular data
- open application
- offline banner not shown

This is because ConnectivityManager.NetworkCallback inside /food2forkcompose/presentation/util/ConnectionLiveData.kt  gets triggered only when:
- A network connection is present (overrides onAvailable())
- A network is lost (overrides onLost())
and not when network is unavailable by default

**Comment by mitchtabian** [comment]
I'm active here https://github.com/mitchtabian/food2fork-compose/pull/4
