### ISSUE TITLE
Checking Internet connection on launch of the application 

### ISSUE THREAD

**Issue by hithamalbasheir** [mitchtabian/food2fork-compose#8]
The Internet connection code works really well, but the problem is that it doesn't work if I started the app with the wifi & cellular closed, so unless I switch on the cellular or wifi first it won't check, any idea of how to resolve this, or should I just delay the code?
I've already "stackoverflowed" 😂 my problem [here](https://stackoverflow.com/q/68679821/8963998)

**Comment by mitchtabian** [comment]
See https://github.com/mitchtabian/food2fork-compose/issues/2. 
I'm unable to reproduce.
