### ISSUE TITLE
The effect of explicitly asserting that the isNetworkAvailable should be false (by default)

### ISSUE THREAD

**Issue by kasem-sm** [mitchtabian/food2fork-compose#9]
As we are defining that the '[isNetworkAvailable](https://github.com/mitchtabian/food2fork-compose/blob/master/app/src/main/java/com/codingwithmitch/food2forkcompose/presentation/util/ConnectivityManager.kt#L18)' boolean value should be false by default (which is a good practice though) but this leads to some issues on a few devices.

Issue -> By default the value of [isNetworkAvailable ](https://github.com/mitchtabian/food2fork-compose/blob/master/app/src/main/java/com/codingwithmitch/food2forkcompose/presentation/util/ConnectivityManager.kt#L18)is false and on some devices, before it asserts whether the user has a valid connection or not (pinging to Google and stuff) the interactor executes so as the default [isNetworkAvailable](https://github.com/mitchtabian/food2fork-compose/blob/master/app/src/main/java/com/codingwithmitch/food2forkcompose/interactors/recipe/GetRecipe.kt#L26) value is false, the interactor doesn't query the API and hence if the cache is not empty the data get emitted but if it's the first start or the cache is empty, no data is emitted. 

@mitchtabian is not experiencing this issue because for tutorial purposes he has added delay in all interactors before isNetworkAvailable line, and hence in that time the value gets asserted i.e true and the interactor queries the API.

**Comment by mitchtabian** [comment]
So the issue is only upon the first app launch? You are saying the results are not being queried? That is not at all what the other issues were describing.
